### ISSUE TITLE
AttributeError:__enter__ with >Python3.8.5 and glob

### ISSUE THREAD

**Issue by ProLoDs** [devopshq/artifactory#181]
Hi,

im using python 3.9 and having an error when trying to `glob()`.
Using  `dohq-artifactory          0.7.382`.

I read about the issues and thought that the error is fixed.

To reproduce, use python3.8.5 or higher and try to use the function `glob()`.

Error in:
```python
Traceback (most recent call last):
  File "C:\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "DEDACTED\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "DEDACTED\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 430, in main    
    run()
  File "DEDACTED\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 267, in run_file
    runpy.run_path(options.target, run_name=compat.force_str("__main__"))
  File "C:\Python39\lib\runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Python39\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "DEDACTED", line 162, in <module>
    main()
  File "DEDACTED", line 149, in main
    for a in BackupStorage().listBackups("tar.gz"):
  File "DEDACTED", line 45, in listBackups
    for element in self.client.glob(f"*.{filesuffix}"):
  File "C:\Python39\lib\pathlib.py", line 1166, in glob
    for p in selector.select_from(self):
  File "C:\Python39\lib\pathlib.py", line 547, in _select_from
    with scandir(parent_path) as scandir_it:
AttributeError: __enter__
```

**Comment by ProLoDs** [comment]
I debugged a little and and found out, that the scandir in _ArtifactoryAccessor overwrites the correct scandir and will crash it.

```
    # https://github.com/devopshq/artifactory/issues/11
    # Added for support python 3.6
    def scandir(self, pathobj):
        for x in _ArtifactoryAccessor.listdir(self, pathobj):
            yield pathobj.joinpath(x)
```

**Comment by ProLoDs** [comment]
This was already fixed in https://github.com/devopshq/artifactory/pull/163.
@allburov When will the next release be made? This issue can be closed afterwards.

**Comment by allburov** [comment]
I think we have already merged these changes to master https://github.com/devopshq/artifactory/blob/master/artifactory.py#L541-L560
Could you try the latest `dohq-artifactory` version? Just be sure that you don't use `artifactory` library (remove file `artifactory.py` from `site-packages`)

**Comment by mkarhumaa** [comment]
I can confirm that bug still exist in `dohq-artifactory` version 0.7.468. I'm using Python 3.8.5.

**Comment by mkarhumaa** [comment]
Sorry about confusion. The problem I saw was indeed in our own code. We had previously overwritten the `ArtifactoryAccessor.scandir` with our own implementation to make it work with Python 3. Apparently that implementation did not work with Python 3.8.5 anymore.

**Comment by ProLoDs** [comment]
Still the latest release v0.7 has the old code. All im asking is a new release. The current master is fine.

**Comment by mkarhumaa** [comment]
@ProLoDs I'm not sure if releases are done in Github anymore. Pypi seems to have latest release 0.7.468: https://pypi.org/project/dohq-artifactory/#history

**Comment by allburov** [comment]
working on it https://github.com/devopshq/artifactory/issues/203

**Comment by allburov** [comment]
We have a new release! https://pypi.org/project/dohq-artifactory/0.7.475/
Could you verify that there is above changes?

**Comment by ProLoDs** [comment]
Looks good! Issue can be closed in my opinion,
